#!/bin/bash
# Install nvm (Node Version Manager)
if ! command -v nvm
then
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | sh
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
fi

# Set the proper node version
NODE_VERSION=$(cat .nvmrc)
if ! nvm use $NODE_VERSION
then
  # Install proper Node version
  nvm install $(cat .nvmrc)
fi

# Assure dependencies are installed
yarn install

# Build
yarn clean-and-check
